

name: Deploy Express App to SmarterASP.NET via Web Deploy

on: [push]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to SmarterASP.NET
        uses: talunzhang/auto-web-deploy@v1.0.1
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: 'build'
